
Vagrant.configure("2") do |config|

  config.vm.box = "dummy"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :aws do |aws, override|
    aws.keypair_name = "id_rsa_mac"

    aws.ami = "ami-0c5204531f799e0c6"
    aws.security_groups = ["sg-0f013965c9505d747"]
    aws.subnet_id = "subnet-d72c7cae"
    aws.tags = {
	  'Name' => 'Vagrant_Machine'
    }
    aws.terminate_on_shutdown = true

    override.ssh.username = "ec2-user"
    config.ssh.keys_only = false
  end
end
