Vagrant.configure("2") do |config|

    config.vm.box = "dummy"

    (1..3).each do |i|
        config.vm.define vm_name = "%s-%01d" % ["kube", i] do |node|
            node.vm.hostname = vm_name
            node.vm.synced_folder '.', '/vagrant', disabled: true

            node.vm.provider :aws do |aws, override|
                aws.keypair_name = "id_rsa_mac"

                aws.ami = "ami-0c5204531f799e0c6"
                aws.security_groups = ["sg-0f013965c9505d747"]
                aws.subnet_id = "subnet-d72c7cae"
                aws.tags = {
                  'Name' => "Vagrant_Machine_#{i}"
                }
                aws.terminate_on_shutdown = true

                override.ssh.username = "ec2-user"
                node.ssh.keys_only = false
            end
        end
    end
end
